### ISSUE TITLE
Week7 Project Assignment Feedback

### ISSUE THREAD

**Issue by twohorse0311** [nthu-servsec-crypto-delta/chitchat-api#8]
1. Not sure what the purpose of this file is. If it's not currently needed, please remove it.
https://github.com/nthu-servsec-crypto-delta/chitchat-api/blob/1794322ffa236df7badcc14a9e0afd56cc529b4f/app/models/location.rb

**Comment by t510599** [comment]
@twohorse0311 Hi, it would be used in this week's new API. Thanks for your feedback!
